export const data = [
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: true,
    },
    {
      name: "Mohamed",
      phone: "+201014426851",
      location: "Giza",
      mail: "mohamed011@gmail.com",
      active: true,
    },
    {
      name: "Elsayed",
      phone: "+201011899462",
      location: "Alexandria",
      mail: "elsayed852@gmail.com",
      active: false,
    },
    {
      name: "Hussin",
      phone: "+201011477896",
      location: "Zagazig",
      mail: "Hussin320@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: true,
    },
    {
      name: "Mohamed",
      phone: "+201014426851",
      location: "Giza",
      mail: "mohamed011@gmail.com",
      active: true,
    },
    {
      name: "Elsayed",
      phone: "+201011899462",
      location: "Alexandria",
      mail: "elsayed852@gmail.com",
      active: false,
    },
    {
      name: "Hussin",
      phone: "+201011477896",
      location: "Zagazig",
      mail: "Hussin320@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: true,
    },
    {
      name: "Mohamed",
      phone: "+201014426851",
      location: "Giza",
      mail: "mohamed011@gmail.com",
      active: true,
    },
    {
      name: "Elsayed",
      phone: "+201011899462",
      location: "Alexandria",
      mail: "elsayed852@gmail.com",
      active: false,
    },
    {
      name: "Hussin",
      phone: "+201011477896",
      location: "Zagazig",
      mail: "Hussin320@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: true,
    },
    {
      name: "Mohamed",
      phone: "+201014426851",
      location: "Giza",
      mail: "mohamed011@gmail.com",
      active: true,
    },
    {
      name: "Elsayed",
      phone: "+201011899462",
      location: "Alexandria",
      mail: "elsayed852@gmail.com",
      active: false,
    },
    {
      name: "Hussin",
      phone: "+201011477896",
      location: "Zagazig",
      mail: "Hussin320@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: true,
    },
    {
      name: "Mohamed",
      phone: "+201014426851",
      location: "Giza",
      mail: "mohamed011@gmail.com",
      active: true,
    },
    {
      name: "Elsayed",
      phone: "+201011899462",
      location: "Alexandria",
      mail: "elsayed852@gmail.com",
      active: false,
    },
    {
      name: "Hussin",
      phone: "+201011477896",
      location: "Zagazig",
      mail: "Hussin320@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: true,
    },
    {
      name: "Mohamed",
      phone: "+201014426851",
      location: "Giza",
      mail: "mohamed011@gmail.com",
      active: true,
    },
    {
      name: "Elsayed",
      phone: "+201011899462",
      location: "Alexandria",
      mail: "elsayed852@gmail.com",
      active: false,
    },
    {
      name: "Hussin",
      phone: "+201011477896",
      location: "Zagazig",
      mail: "Hussin320@gmail.com",
      active: false,
    },
    {
      name: "Mostafa",
      phone: "+201282313371",
      location: "Egypt",
      mail: "mstfa.mhmd22@gmail.com",
      active: false,
    },
  ];